repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=1024"]
      - id: check-merge-conflict
      - id: detect-aws-credentials
        args:
          - "--allow-missing-credentials"
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-yaml
        args:
          - "--allow-multiple-documents"
  - repo: https://github.com/sirosen/texthooks
    rev: 0.6.6
    hooks:
      - id: fix-smartquotes
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
      - id: go-fmt
        args: [-s, -w, ./test]
      - id: golangci-lint
        args:
          - "--timeout=10m"
          - "--verbose"
          - "--allow-parallel-runners"
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.91.0
    hooks:
      - id: terraform_fmt
        args:
          - --hook-config=--tf-path=tofu
      - id: terraform_tflint
        args:
          - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
          - --hook-config=--tf-path=tofu
  - repo: https://github.com/tofuutils/pre-commit-opentofu
    rev: v1.0.3 # Get the latest from: https://github.com/tofuutils/pre-commit-opentofu/releases
    hooks:
      - id: tofu_docs
        args:
          - --args=--lockfile=false
          - --hook-config=--path-to-file=README.md # Valid UNIX path. I.e. ../TFDOC.md or docs/README.md etc.
          - --hook-config=--add-to-existing-file=true # Boolean. true or false
          - --hook-config=--create-file-if-not-exist=true # Boolean. true or false
      - id: tofu_checkov
        args:
          - --args=--config-file __GIT_WORKING_DIR__/.checkov.yml
  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 37.410.2
    hooks:
      - id: renovate-config-validator
